language: node_js
node_js:
  - "7"
  - "6"
  - "5"
env:
  - CXX=g++-4.8
script:
  - npm test
after_success:
  - npm run coverage
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
